name: Build iOS IPA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install MAUI
        run: dotnet workload install maui --ignore-failed-sources
      - name: Clean
        run: rm -rf bin obj Release */bin */obj
      - name: Find and Build IPA
        run: |
          CSPROJ=$(find . -name "DualAudioSync.csproj" | head -n 1)
          echo "Encontrado: $CSPROJ"
          dotnet restore "$CSPROJ"
          dotnet publish "$CSPROJ" -f net9.0-ios -c Release -p:BuildIpa=True -p:ArchiveOnBuild=True -p:RuntimeIdentifier=ios-arm64 -p:EnableCodeSigning=false
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa-file
          path: "**/*.ipa"
